// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6eb56fjVAXTMOfi3qbgfs_erpPJchVvw',
    appId: '1:468384957010:web:3d5e25d8d874eff5aed58b',
    messagingSenderId: '468384957010',
    projectId: 'flutterappandyfer',
    authDomain: 'flutterappandyfer.firebaseapp.com',
    storageBucket: 'flutterappandyfer.appspot.com',
    measurementId: 'G-KKPR9760BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1WZ1jRfKOJpQoZoXS08NFm0etH4sQNoM',
    appId: '1:468384957010:android:a799830851d256b4aed58b',
    messagingSenderId: '468384957010',
    projectId: 'flutterappandyfer',
    storageBucket: 'flutterappandyfer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASKs9G7xBp3knIZ0t0PIAZ8kwVRw-WZC0',
    appId: '1:468384957010:ios:b51415864d777d78aed58b',
    messagingSenderId: '468384957010',
    projectId: 'flutterappandyfer',
    storageBucket: 'flutterappandyfer.appspot.com',
    iosClientId: '468384957010-hnoj3pk32880680t31beftucv0d1pgrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.listasFlutter',
  );
}
